name: Create Repository Dispatch
on: push
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dispatch
        uses: ./
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          repositories: |
            guilouro/csv-to-html
            guilouro/multiple-repositories-dispatch
          event_type: test_dispatch
          client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
